/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0a868b90-0e2e-4b06-8931-ac6b7eeea79f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IxcuFPUWB",
    "aws_user_pools_web_client_id": "4jv4k6pl56itc684jaubkfpicv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://34lj3cwkcrhtlbvrtq7jvfba3a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "song-storage185412-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
